version: '2'
messages:
  $i18n: locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  icon: icon.svg
  required:
    - build
    - repo
  info:
    git url: >-
      [{{repository}}]({{repository}})
toolchain:
  name: '{{form.pipeline.parameters.app-name}}'
  template:
    getting_started:
      $ref: '#/messages/toolchain.getting_started'
services:
  repo:
    service_id: hostedgit
    parameters:
      repo_name: '{{form.pipeline.parameters.app-name}}'
      repo_url: '{{repository}}'
      type: clone
      has_issues: true
      enable_traceability: true
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: '{{toolchain.name}}'
      ui-pipeline: true
      configuration:
        content:
          $text: pipeline.yml
        env:
          REPO: repo
          CF_APP: '{{form.pipeline.parameters.app-name}}'
          CF_SPACE: '{{form.pipeline.parameters.dev-space}}'
          CF_ORGANIZATION: '{{form.pipeline.parameters.dev-organization}}'
          CF_REGION_ID: '{{form.pipeline.parameters.dev-region}}'
        execute: true
  webide:
    service_id: orion
form:
  pipeline:
    parameters:
      dev-region: '{{region}}'
      dev-organization: '{{organization}}'
      dev-space: dev
      app-name: '{{baseName}}-{{timestamp}}'
    schema:
      $ref: deploy.json
